spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: true
        show_sql: true
      #        format_sql: true
      javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      javax.cache.uri: classpath:ehcache.xml

  cache:
    type: jcache

logging:
  level:
    org.springframework.cache: INFO
    org.ehcache: INFO

security:
  authentication:
    jwt:
      secret-key: ADJKLSADJKLsjdjkUEHheFDJFHDJHJDHFkjfsdjfkjsfsieufieujzxxxxoiefuwpe0wOISUdfhzdjfhaishiohzjhsfiusfgfgisugfsgfawwhyfoaw
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
